#+title: Brain Tool Design
* Introduction
This file gives an overview of the major components of the BrainTool browser extension. From a users perspective BrainTool (or BT) has a number of components. The Topic Manager runs in a tab, panel window or the browser sidepanel. It shows a hierarchy of 'topics' and contained links to web pages, plus notes and to-do annotation. The Bookmarker is invoked when the extension icon is clicked. It allows the current tab, tabgroup or page to be saved into the Topic Manager. The Sidepanel is just a shell which runs the topic manager in an iframe in the browsers sidepanel. Behind the scenes the service worker code deals with browser interaction, forwards events to the topic manager, and performs actions on the topic managers behalf.
The Topic Manager code is served from the braintool.org site hosted on github. It saves user data in org-mode format to browser local storage with optional file backup.

* General
The BT codebase is plain vanilla javascript, html and CSS. The Topic Manager makes heavy use of JQuery and the jquery treetable widget. It also uses a forked version of orga.js to parse org-mode and a css library called wenk.css for mouse over messages. The extension code does not use jquery or any libraries other than the awesomeplete autocompletion code.

* Components
BrainTool is composed of extension code that runs inside the browser, app code that is served from the github repository and a set of markdown files and resources which compose the braintool.org web site.

** Extension
Extension code is all contained in the /extension directory. This directory is compressed and uploaded to the browser app store. The extension code is modularized with import/export annotations.
*** Service worker
The service worker code is mainly contained in background.js. This code registers for events and forwards them to the application. It also listens for messages from the app and sends back required information.
*** Bookmarker popup
The popup.* files and the topic*.js files handles the Bookmarker interaction.
*** Content Script
The content script code is injected into the tab running the Topic Manager (served from braintool.org). It relays messages between the extension and the application.
*** SidePanel
The sidepanel.* js html code provides a slim wrapper that runs the topic manager in an iframe and mediates communication.

** App
The application code is all contained in the /app directory. It is broken down into a set of components but a lot of the code is in one big bt.js file. All the app code runs in the same namespace and is not yet modularized. Ideally bt.js would be broken up and it and all the other code would be modularized with explicit import/export.
*** bt.js
This file performs a number of major functions
**** Launch activities
**** Table creation and general UI setup
**** Drag and Drop functions
**** Browser Event handling and Bookmarker operations
**** Table row actions
**** Search and Filter operations
**** Keyboard event handling
*** BTNode, BTAppNode
The BT Topic Manager table shows a hierarchy of 'nodes' where each node corresponds to a heading in the underlying org-mode data structure and to a row in the treetable in the UI. Each node models either a bookmark or saved web page (aka 'items'), or a topic which contains a set of saved items. Node items may also have an associated open tab in the browser. Topics are shown in the browser as tab groups and so topic nodes may also have an associated open tab group. A global AllNodes array holds the nodes. It is created on startup from the org data loaded in from local storage (or backup file) and may be sparse (due to item deletion).

The BTNode.js defines the base class of BTNode which handles containment and basic node operations.

The BTAppNode.js file handles the BTAppNode subclass of BTNode which handles all the operations of the nodes in terms of their being org-mode items in a file and being saved and potentially open tabs and tab groups, as well as being rows in the topic table.

There is also a BTLink subclass which represents a url embedded in the org data but not structured as an org header. This is a side effect of trying to support the import of any org-structured file and subsequently showing a clickable link in the tree. IT does not arise in normal BT usage and can generally be ignored.
*** parser.js orga-bundlev2.js
The orgabundlev2.js file contains the org-mode parsing code. The parser.js file is a wrapper which uses the orga code to read org text and create BTNodes and to write org to save BTNode data.
*** jquery.treetable
This is a forked version of the jquery treetable widget which handles the basic operations of creating and displaying the topic tree.
*** fileManager.js, localFileManager.js, gDriveFileManager.js
These files handle reading and writing the BT saved data, in org format, to a local or GDrive file. As well as providing notifications when the files may be out of date.
*** configManager.js
Handles preference/settings and config operations
*** bookmarksManager.js
Handles the import and export of browser bookmarks and the interaction with the browser bookmarks bar.
*** messageManager.js
Handles the display of intro slides that are shown on first install and banner messages that are shown on startup and when a new version is served.
*** subscriptionManager.js
Handles the interaction with a backend Firestore server which integrates with Stripe to allow permanent license purchase and monthly or annual subscriptions.
*** index.html
Contains all the markup for the application and is the central point from which the code files are loaded from cdn (in the case of jquery etc) and the braintool.org server.
*** bt.css, jquery.treetable.css, wenk.css
Between them these files contain all the application css. wenk.css is a standalone library for toolips.

* Build Process
The extension is manually bundled into a tar file and submitted to the store. To be able to handle different versions of the extension codebase simultaneously across users the extension specifies a version and the /app code specific to that version is loaded into the Topic Manager tab when its launched. While /app and /extension have the latest code the /versions hierarchy has the supported production versions. For the purposes of new development and examining the codebase LLM's should ignore the /versions hierarchy in order to avoid expired conventions or old message APIs etc.

At runtime when the Bookmarker popup is initially clicked the index.html file is loaded and orchestrates the loading of the rest of the app via <script> statements


* Refactor
The Refactor project will migrate BrainTool to import/export modules, add a bundler and ideally actually modularize and reduce dependancies to make the code easier to maintain and enhance. 

** impot/export
We'll take a big-bang approach to add imports from everything to the top of every file in app/*.js and export * at the bottom; need to take care of cycles; don't redefine globals like AllNodes -> wrapper setter/getter? 

** Break bt.js and index.html
We'll then break bt.js into its component parts and parcel out ui creation. Specifically we'll create an applicationUI component that will generate the html for the #controlsHeader and .settingsActions and the #footer elements, move the messageContainer ui creation into the messageManager, and move the table content code out of bt.js into its own module. We'll update the imports/exports and dependencies as we go, examining any opportunity to cut some dependencies by inverting them via event registration or other such methods and overall compose independent subsystems.

** Pull out special node handling
special nodes like bookmarks bar, session nodes (see below) etc should register for node changes rather than every mutation having to call out to them from bt.js 

** revisit dependencies
The initial big bang left a bunch of circular dependencies that need to be resolved. We'll need to carefully analyze the imports/exports and refactor the code to eliminate those that remain after the other steps are completed. 

* Bookmarker summaries
The Summaries project will make use of the browsers ai summarizer to optionally populate the notes field in the BT Bookmarker window with a summary of selected text or the whole page. The page text will be extracted using a version of the readability.js library.

* The SessionManager project 
The SessionManager project will create a new type of special topic which shows the current live session. Maybe use a subclass to override when needed?


* Application components and modules dependency map
perl -0777 -ne 'while (/^(import|export)\s*\{[^}]*\}.*?;/gsm) { print "$ARGV: $&\n" }' *.js
** EstensionMessaging - abstracted out app to extension messaging that everyone depends on
extensionMessaging.js: export { sendMessage, callBackground };
** BTNode - Base node management, holder of AllNodes
BTNode.js: export { BTNode, AllNodes };
** configManager.js - store and manage configurations and stats. should migrate localStorage to here from localFileManager?
configManager.js: import { sendMessage } from './extensionMessaging.js';
configManager.js: export {
    setConfigAndKeys,
    setProp,
    getProp,
    metaPropertiesToString,
    setStat,
    incrementStat,
    initializeInstallDate
};
** BTAppNode - Generates ui elements, org, Search support at row level, tab operations via background, utilities across application items (eg ListOpenTabs) that are mostly used by rowManager, handling special topics, BTLink class which manaegs links contained in org data.
BTAppNode.js: import { BTNode, AllNodes } from './BTNode.js';
BTAppNode.js: import { getProp, incrementStat, metaPropertiesToString } from './configManager.js';
BTAppNode.js: import { sendMessage, callBackground } from './extensionMessaging.js';
BTAppNode.js: import { localStorageManager } from './localFileManager.js';                      // Local storage used for favicons. break out from localFileStorage?
BTAppNode.js: export { BTAppNode, BTLinkNode, Topics };                 // pretty much exports the kitchen sink.
** rowManager - companion to AppNode, handles application logic for rows (eg node deletion => update browser tab, update parent and ancestor open state in table). Maybe should be shuffled into place with AppNode to localize behavior updates
rowManager.js: import { AllNodes, BTNode } from './BTNode.js';
rowManager.js: import { BTAppNode, Topics } from './BTAppNode.js';
rowManager.js: import { getProp, setProp, incrementStat } from './configManager.js';
rowManager.js: import { callBackground } from './extensionMessaging.js';
rowManager.js: import { saveBT } from './fileManager.js';
rowManager.js: import { exportBookmarksBar } from './bookmarksManager.js';
rowManager.js: import { initializeUI, Resizing } from './tableManager.js';
rowManager.js: export {
    buttonShow,
    buttonHide,
    editRow,
    closeDialog,
    openRow,
    closeRow,
    deleteRow,
    deleteNode,
    updateRow,
    toDo,
    promote,
    addNewTopLevelTopic,
    addChild,
    cancelEdit,
    initializeButtonRow,
    toggleMoreButtons
};
** tableManager - works w rowManager, btAppNode, and bt.js to run the show
tableManager.js: import { getProp, setProp } from './configManager.js';
tableManager.js: import { closeConfigDisplays, updatePrefs } from './applicationUI.js';
tableManager.js: import { messageManager } from './messageManager.js';
tableManager.js: import { AllNodes, BTNode } from './BTNode.js';
tableManager.js: import { BTAppNode, Topics } from './BTAppNode.js';
tableManager.js: import { parseBTFile } from './parser.js';
tableManager.js: import { sendMessage } from './extensionMessaging.js';
tableManager.js: import { getBTFile, getBTFileText, savePendingP, saveBT, updateSyncSettings, syncEnabled, updateStatsRow } from './fileManager.js';
tableManager.js: import { buttonShow, buttonHide, deleteNode } from './rowManager.js';
tableManager.js: import { exportBookmarksBar } from './bookmarksManager.js';
tableManager.js: export {
    refreshTable,
    processBTFile,
    initializeNotesColumn,
    initializeUI,
    moveNode,
    Resizing
};
** applicationUI - generates all the markup for the header, footer and settings/actions/help panels. Handles open/close and associated ui updates to change settings etc
applicationUI.js: import { sendMessage } from './extensionMessaging.js';
applicationUI.js: import { getProp, setProp } from './configManager.js';
applicationUI.js: import { searchButton, filterToDos, filterSearch, groupingUpdate } from './bt.js';
applicationUI.js: import { addNewTopLevelTopic, toggleMoreButtons } from './rowManager.js';
applicationUI.js: import { refreshTable } from './tableManager.js';
applicationUI.js: import { handlePurchase, openStripePortal, importKey } from './subscriptionManager.js';
applicationUI.js: import { importBookmarks, exportBookmarks } from './bookmarksManager.js';
applicationUI.js: import { importOrgFile, importTabsOutliner, exportOrgFile, stopSyncing, initiateBackups, authorizeGAPI, authorizeLocalFile } from './fileManager.js';
applicationUI.js: export { initializeControlsHeader, initializeSettings, initializeActions, initializeHelp, initializeFooter, closeConfigDisplays, updatePrefs };
** Mains app logic. handles startup, browser events, search, key commands
bt.js: import { sendMessage, callBackground } from './extensionMessaging.js';
bt.js: import { BTNode, AllNodes } from './BTNode.js';
bt.js: import { setConfigAndKeys, getProp, setProp, setStat, incrementStat, initializeInstallDate } from './configManager.js';
bt.js: import { messageManager } from './messageManager.js';
bt.js: import { BTAppNode, Topics } from './BTAppNode.js';
bt.js: import { saveBT, syncEnabled, handleStartupFileConnection, updateStatsRow, checkBTFileVersion, setBTFileText } from './fileManager.js';
bt.js: import { loadBookmarks, syncBookmarksBar, bookmarksBarIds, registerProcessImport as registerProcessImportBM } from './bookmarksManager.js';
bt.js: import { checkLicense } from './subscriptionManager.js';
bt.js: import { refreshTable, processBTFile, initializeNotesColumn, initializeUI, moveNode } from './tableManager.js';
bt.js: import { deleteNode, openRow, closeRow, toDo, editRow, deleteRow, addChild, promote } from './rowManager.js';
bt.js: import { registerProcessImport as registerProcessImportParser } from './parser.js';
bt.js: import { closeConfigDisplays } from './applicationUI.js'
bt.js: export {
    searchButton, filterSearch, filterToDos,
    syncEnabled, updateStatsRow, groupingUpdate
};
** fileManager - common backing store management and facade for local/gdrive file operations. also imports/exports of org and tabsOutliner data
fileManager.js: import { getProp, setProp, incrementStat } from './configManager.js';
fileManager.js: import { sendMessage } from './extensionMessaging.js';
fileManager.js: import { AllNodes } from './BTNode.js';
fileManager.js: import { BTAppNode } from './BTAppNode.js';
fileManager.js: import { localFileManager } from './localFileManager.js';
fileManager.js: import { gDriveFileManager } from './gDriveFileManager.js';
fileManager.js: import { messageManager } from './messageManager.js';
fileManager.js: import { insertOrgFile } from './parser.js';
fileManager.js: export {
    saveBT, getBTFile, initiateBackups, syncEnabled, handleStartupFileConnection,
    updateSyncSettings, savePendingP,
    importOrgFile, importTabsOutliner, exportOrgFile, stopSyncing, updateStatsRow,
    getBTFileText, setBTFileText, checkBTFileVersion,
    authorizeGAPI, authorizeLocalFile
};

gDriveFileManager.js: import { getProp, setProp } from './configManager.js';
gDriveFileManager.js: export { gDriveFileManager };

localFileManager.js: import { setProp, getProp } from './configManager.js';
localFileManager.js: export { localFileManager, localStorageManager };
** bootmarksManager - bookmarks import/export and bookmarksBar syncing
bookmarksManager.js: import { sendMessage } from './extensionMessaging.js';
bookmarksManager.js: import { BTAppNode } from './BTAppNode.js';
bookmarksManager.js: import { AllNodes } from './BTNode.js';
bookmarksManager.js: export { importBookmarks, loadBookmarks, syncBookmarksBar, exportBookmarksBar, bookmarksBarIds, exportBookmarks, registerProcessImport };
** messageManager - handles intro slides on first install and message banner. Need to change set config vars that say how to start vs current buttons w dependencies
messageManager.js: import { getProp, setProp } from './configManager.js';
messageManager.js: import { sendMessage } from './extensionMessaging.js';           // remove when bookmarks/session sync is set as an option
messageManager.js: import { importBookmarks } from './bookmarksManager.js';
messageManager.js: export { messageManager, initializeMessageContainer, initializeIntro };
** parser - wrapper for orga org parser code.
parser.js: import { setProp } from './configManager.js';
parser.js: import { BTAppNode, BTLinkNode } from './BTAppNode.js';
parser.js: export { parseBTFile, insertOrgFile, registerProcessImport };
** subscriptionManager - shoudl be called purchaseManager? handles stripe/firebase interaction to get license
subscriptionManager.js: import { getProp, setProp } from './configManager.js';
subscriptionManager.js: export { handlePurchase, openStripePortal, checkLicense, importKey};
** index = main entry point. imports shold go away when edit overlay is abstracted out
index.html: import { closeDialog, cancelEdit, updateRow } from './rowManager.js';
